version: '3'

services:
    redis:
            image: redis
            container_name: redis
            ports:
                - 6379:6379
            networks:
                app-network:
                    ipv4_address: 10.0.0.9

    python:
        container_name: python
        build:
            context: .
            dockerfile: python.dockerfile
        ports:
            - 80:8000
        volumes:
            - ./:/code
        depends_on:
            - redis
        networks:
                app-network:
                    ipv4_address: 10.0.0.7

networks:
    app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/16"